labels:
  - source: "SOS_ICD10-SE"
    icd: "ICD-10"
    lang: "sv"
    delimiter: "\t"
    filter: "^[A-Z]"
    code_column: "Kod"
    label_column: "Titel"

  - source: "SOS_ICD10-SE"
    icd: "ICD-10"
    lang: "la"
    delimiter: "\t"
    filter: "^[A-Z]"
    code_column: "Kod"
    label_column: "Latin"

  - source: "SOS_ICD9-SE"
    icd: "ICD-9"
    lang: "sv"
    code_column: "KOD"
    replacements:
      - pattern: 'A$'
        replace: '0'
      - pattern: 'B$'
        replace: '1'
      - pattern: 'C$'
        replace: '2'
      - pattern: 'D$'
        replace: '3'
      - pattern: 'E$'
        replace: '4'
      - pattern: 'F$'
        replace: '5'
      - pattern: 'G$'
        replace: '6'
      - pattern: 'H$'
        replace: '7'
      - pattern: 'W$'
        replace: '8'
      - pattern: 'X$'
        replace: '9'
    label_column: "KODTEXT"

  - source: "SOS_ICD8-SE"
    icd: "ICD-8"
    lang: "sv"
    code_column: "Kod"
    label_column: "Text"

  - source: "CDC_ICD10-CM"
    icd: "ICD-10"
    lang: "en"
    delimiter: "\t"
    code_column: 0
    label_column: 1

  - source: "EJE_ICD8-ICD10"
    icd: "ICD-8"
    lang: "la"
    code_column: "ICD8_CODE"
    label_column: "ICD8_TEXT"

sources:
  SOS_ICD10-SE:
    title: "Socialstyrelsen ICD-10-SE"
    publisher: "Socialstyrelsen (Swedish National Board of Health and Welfare)"
    path: "data/SOS_ICD10-SE.tsv"
    reference: "https://www.socialstyrelsen.se/globalassets/sharepoint-dokument/dokument-webb/klassifikationer-och-koder/icd-10-se.tsv"
    doi: ""
    version: "2024-12-09"
    retrieved_at: "2025-09-23"
    license: "Unknown"
    notes: "Official Swedish classification ICD-10-SE, valid from 2025-01-01"

  SOS_ICD9-SE:
    title: "Socialstyrelsen ICD-9-SE"
    publisher: "Socialstyrelsen (Swedish National Board of Health and Welfare)"
    path: "data/SOS_ICD9-SE.xls"
    reference: "https://www.socialstyrelsen.se/globalassets/sharepoint-dokument/dokument-webb/klassifikationer-och-koder/icd-9-klassifikation-av-sjukdomar-1987-ks87.xls"
    doi: ""
    version: ""
    retrieved_at: "2025-09-23"
    license: "Unknown"
    notes: >
      Official Swedish classification ICD-9-SE. The original version of ICD-9-SE used letters instead of digits after the decimal point (A=0, B=1, C=2, D=3, E=4, F=5, G=6, H=7, W=8, X=9).

  SOS_ICD8-SE:
    title: "Socialstyrelsen ICD-8-SE"
    publisher: "Socialstyrelsen (Swedish National Board of Health and Welfare)"
    path: "data/SOS_ICD8-SE.xls"
    reference: "https://www.socialstyrelsen.se/globalassets/sharepoint-dokument/dokument-webb/klassifikationer-och-koder/icd-8-klassifikation-av-sjukdomar-mm-1968.xls"
    doi: ""
    version: ""
    retrieved_at: "2025-09-23"
    license: "Unknown"
    notes: "Official Swedish classification ICD-8-SE."

  CDC_ICD10-CM:
    title: "English labels for ICD-10-CM"
    publisher: "https://cdc.gov/"
    reference: "https://ftp.cdc.gov/pub/health_statistics/nchs/publications/ICD10CM/2018/2018-ICD-10-CM-Codes-File.zip (icd10cm_codes_2018.txt)"
    path: "data/CDC_ICD10-CM.txt"
    doi: ""
    version: "2018"
    retrieved_at: "2025-09-25"
    license: "Public domain"
    language: "English"
    notes: "Provides English ICD labels for ICD-10-CM."

  EJE_ICD8-ICD10:
    title: "A unidirectional mapping of ICD-8-DK to ICD-10-DK codes (provides labels for ICD-8 codes in Latin)"
    publisher: "Pedersen, M.K., Eriksson, R., Reguant, R. et al. A unidirectional mapping of ICD-8 to ICD-10 codes, for harmonized longitudinal analysis of diseases. Eur J Epidemiol 38, 1043–1052 (2023). https://doi.org/10.1007/s10654-023-01027-y"
    path: "data/EJE_ICD8-ICD10.txt"
    reference: "https://static-content.springer.com/esm/art%3A10.1007%2Fs10654-023-01027-y/MediaObjects/10654_2023_1027_MOESM1_ESM.txt"
    version: "2023-09-09"
    retrieved_at: "2025-09-25"
    license: "Creative Commons Attribution 4.0 International License"
    notes: "Mapping scores: 1 (a straightforward match, 2 (a good match), 3 (an acceptable match), and 5 (the best possible match, poor quality match). Difficult matches flagged with one or more of seven flags (A-G) highlighting the mapping problem."