labels:
  - source: "SOS_ICD10-SE"
    icd: "ICD-10"
    lang: "sv"
    delimiter: "\t"
    filter: "^[A-Z]"
    code_column: "Kod"
    label_column: "Titel"

  - source: "SOS_ICD9-SE"
    icd: "ICD-9"
    lang: "sv"
    code_column: "KOD"
    replacements:
      - pattern: 'A$'
        replace: '0'
      - pattern: 'B$'
        replace: '1'
      - pattern: 'C$'
        replace: '2'
      - pattern: 'D$'
        replace: '3'
      - pattern: 'E$'
        replace: '4'
      - pattern: 'F$'
        replace: '5'
      - pattern: 'G$'
        replace: '6'
      - pattern: 'H$'
        replace: '7'
      - pattern: 'W$'
        replace: '8'
      - pattern: 'X$'
        replace: '9'
    label_column: "KODTEXT"

  - source: "SOS_ICD8-SE"
    icd: "ICD-8"
    lang: "sv"
    code_column: "Kod"
    label_column: "Text"

  - source: "KAGGLE_ICD10-CM"
    icd: "ICD-10"
    lang: "en"
    delimiter: ","
    code_column: 2
    label_column: 4

sources:
  SOS_ICD10-SE:
    title: "Socialstyrelsen ICD-10-SE"
    publisher: "Socialstyrelsen (Swedish National Board of Health and Welfare)"
    path: "data/SOS_ICD10-SE.tsv"
    reference: "https://www.socialstyrelsen.se/globalassets/sharepoint-dokument/dokument-webb/klassifikationer-och-koder/icd-10-se.tsv"
    doi: ""
    version: "2024-12-09"
    retrieved_at: "2025-09-23"
    license: "Unknown"
    notes: "Official Swedish classification ICD-10-SE, valid from 2025-01-01"

  SOS_ICD9-SE:
    title: "Socialstyrelsen ICD-9-SE"
    publisher: "Socialstyrelsen (Swedish National Board of Health and Welfare)"
    path: "data/SOS_ICD9-SE.xls"
    reference: "https://www.socialstyrelsen.se/globalassets/sharepoint-dokument/dokument-webb/klassifikationer-och-koder/icd-9-klassifikation-av-sjukdomar-1987-ks87.xls"
    doi: ""
    version: ""
    retrieved_at: "2025-09-23"
    license: "Unknown"
    notes: >
      Official Swedish classification ICD-9-SE. The original version of ICD-9-SE used letters instead of digits after the decimal point (A=0, B=1, C=2, D=3, E=4, F=5, G=6, H=7, W=8, X=9).

  SOS_ICD8-SE:
    title: "Socialstyrelsen ICD-8-SE"
    publisher: "Socialstyrelsen (Swedish National Board of Health and Welfare)"
    path: "data/SOS_ICD8-SE.xls"
    reference: "https://www.socialstyrelsen.se/globalassets/sharepoint-dokument/dokument-webb/klassifikationer-och-koder/icd-8-klassifikation-av-sjukdomar-mm-1968.xls"
    doi: ""
    version: ""
    retrieved_at: "2025-09-23"
    license: "Unknown"
    notes: "Official Swedish classification ICD-8-SE."

  KAGGLE_ICD10-CM:
    title: "Kaggle ICD-10-CM"
    publisher: "https://www.kaggle.com/"
    path: "data/KAGGLE_ICD10-CM.csv"
    reference: "https://www.kaggle.com/datasets/arashnic/icd10-codes-and-descriptions"
    doi: ""
    version: "2024-01-21"
    retrieved_at: "2025-09-23"
    license: "CC0: Public Domain"
    notes: "ICD10 codes and descriptions"