mappings:
  - source: "SOS_ICD9-ICD10"
    sheet: 1
    from_icd: "ICD-9"
    from_column: "ICD-9"
    to_icd: "ICD-10"
    to_column: "ICD-10"
    attributes:
      - R
      - R1
      - R2

  - source: "EJE_ICD8-ICD10"
    from_icd: "ICD-8"
    from_column: "ICD8_CODE"
    to_icd: "ICD-10"
    to_column: "ICD10_CODE"
    attributes:
      - MAPPING_SCORE
      - MAPPING_FLAG

sources:
  SOS_ICD9-ICD10:
    title: "Socialstyrelsen ICD-9 to ICD-10 conversion table"
    publisher: "Socialstyrelsen (Swedish National Board of Health and Welfare)"
    path: "data/SOS_ICD9-ICD10.xls"
    reference: "https://www.socialstyrelsen.se/globalassets/sharepoint-dokument/dokument-webb/klassifikationer-och-koder/konverteringstabell-icd9-icd10-forklaring-exempel.xls"
    retrieved_at: "2025-09-23"
    license: "Unknown"
    notes: >
      Official Swedish crosswalk; fields R/R1/R2 are mapping ratings.
      The value R indicates how codes on the left and right side of the table correspond, normally starting from the left-hand column. If R = 1, the two codes are fully equivalent. If R = 2, the ICD-10 code in column A is more detailed than the ICD-9 code in column B, meaning several ICD-10 codes may be needed to match a single ICD-9 code. If R = 3, the situation is reversed: the ICD-10 code is less detailed, and several ICD-9 codes may be required to represent the same content. When R = 4, the relationship is more complex: neither system has unique one-to-one matches, and one code from either side can correspond to several codes on the other side. If R = 5, there is no correspondence at all. In addition, R1 specifies how many codes from ICD-9 are needed to match a code in ICD-10, while R2 specifies how many codes from ICD-10 are required to match a code in ICD-9.
    
  EJE_ICD8-ICD10:
    title: "A unidirectional mapping of ICD-8-DK to ICD-10-DK codes"
    publisher: "Pedersen, M.K., Eriksson, R., Reguant, R. et al. A unidirectional mapping of ICD-8 to ICD-10 codes, for harmonized longitudinal analysis of diseases. Eur J Epidemiol 38, 1043–1052 (2023). https://doi.org/10.1007/s10654-023-01027-y"
    path: "data/EJE_ICD8-ICD10.txt"
    reference: "https://static-content.springer.com/esm/art%3A10.1007%2Fs10654-023-01027-y/MediaObjects/10654_2023_1027_MOESM1_ESM.txt"
    version: "2023-09-09"
    retrieved_at: "2025-09-25"
    license: "Creative Commons Attribution 4.0 International License"
    notes: "Mapping scores: 1 (a straightforward match, 2 (a good match), 3 (an acceptable match), and 5 (the best possible match, poor quality match). Difficult matches flagged with one or more of seven flags (A-G) highlighting the mapping problem."